<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="Gridview_task2.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
     integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title></title>
</head>
<body>
     
    <div class="container d-inline-flex justify-content-center m-5 ">
    <form id="form1" runat="server">
        <div>
            <div class="row navbar navbar-expand-sm bg-dark ">
            <div class="col-sm-10 " >
                <asp:TextBox ID="TextSearch" runat="server" Class="form-control"></asp:TextBox>

            </div>
            <div class="col-sm-2" >
                <asp:Button ID="Search" runat="server" Text="Search" OnClick="Search_Click" class="btn btn-outline-primary  btn-toolbar form-control justify-content-center" />
            </div>
            </div>
            
            
            <br />
            <br />

            <asp:GridView ID="GridView1" runat="server"  class=" table text-center table-hover table-dark  table-bordered "
                Width="800px" AllowPaging="True" DataKeyNames="ID" OnPageIndexChanging="GridView1_PageIndexChanging" 
                OnSelectedIndexChanged="GridView1_SelectedIndexChanged" PageSize="15"  AutoGenerateColumns="False" 
                OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" AutoGenerateSelectButton="True" OnRowDeleting="GridView1_RowDeleting"   >
                <Columns>
                    
                    <asp:TemplateField HeaderText="Operation">
                        <EditItemTemplate>
                            <asp:LinkButton ID="LinkButton_Update" runat="server" CommandName="update">Update</asp:LinkButton>
                            &nbsp;
                            <asp:LinkButton ID="LinkButton_Cancel" runat="server" CommandName="cancel">Cancel</asp:LinkButton>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:LinkButton ID="Edit" runat="server" CommandName="edit">Edit</asp:LinkButton>
                            &nbsp;
                            <asp:LinkButton ID="LinkButton_Delete" CommandName="delete" runat="server">Delete</asp:LinkButton>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Name">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox_Name" runat="server" Text='<%# Eval("Name") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Name" runat="server" Text='<%# Eval("Name") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="ID">
                        <ItemTemplate>
                            <asp:Label ID="ID" runat="server" Text='<%# Eval("ID") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Role">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox_Role" runat="server" Text='<%# Eval("Role") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Role" runat="server" Text='<%# Eval("Role") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            
            </asp:GridView>



            <br />
            <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="800px" AutoGenerateDeleteButton="True" OnModeChanging="DetailsView1_ModeChanging" AutoGenerateRows="False"  class=" table text-center table-hover table-dark  table-bordered " >
                <Fields>
                    <asp:BoundField DataField="Name" HeaderText="Name" />
                    <asp:BoundField DataField="ID" ReadOnly="true" HeaderText="ID" />
                    <asp:BoundField DataField="Role" HeaderText="Role" />
                </Fields>
            </asp:DetailsView>



        </div>
    </form>
        </div>
</body>

</html>
